name: Test Eslint

on:
  pull_request:
    types:
      - opened
      - synchronize

  jobs:
    eslint:
      runs-on: unbuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Eslint Check
        run: npm run lint
